/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.waregame;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author semje
 */
public class AffichageSauvegarde extends javax.swing.JFrame {

    /**
     * Creates new form AffichageSauvegarde
     */
    int choix = 0 ;
    
    public AffichageSauvegarde() {
        initComponents();
        
        message.setForeground( new Color(0,102,0));
        message.setText("Cliquez sur une sauvegarde");
        
        Waregame.tableauDesauvegarde = Sauvegarde.getToutesLesSauvegardes();
        
        DefaultTableModel model = (DefaultTableModel) jT_sauvegarde.getModel();
        
        //String[][] tabclients = Miniprojetjava.baseDeDonnees.getClientNonSupprimes();
        
        for(int i=0 ; i < Waregame.tableauDesauvegarde.length ; i++ ){
            //System.out.println(Waregame.tableauDesauvegarde[i].date_sauvegarde);
            Object[] rowData = {Waregame.tableauDesauvegarde[i].nom_joueur1, Waregame.tableauDesauvegarde[i].num_tour_joueur1, Waregame.tableauDesauvegarde[i].nom_joueur2, Waregame.tableauDesauvegarde[i].num_tour_joueur2, Waregame.tableauDesauvegarde[i].date_sauvegarde };
            model.addRow(rowData);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_sauvegarde = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Charger données");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jT_sauvegarde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom joueur 1 ", "Numero de tour joueur 1", "Nom joueur 2", "Numero de tour joueur 2", "Date de la partie"
            }
        ));
        jT_sauvegarde.setGridColor(new java.awt.Color(255, 255, 255));
        jT_sauvegarde.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jT_sauvegarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_sauvegardeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_sauvegarde);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Liste des parties sauvegardées");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Continuer la partie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("message");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_sauvegardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_sauvegardeMouseClicked

        try{
            
            choix = jT_sauvegarde.getSelectedRow(); 
            System.out.println(choix);
            
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
        
    }//GEN-LAST:event_jT_sauvegardeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jT_sauvegarde.getSelectedRow() == -1){
            if(jT_sauvegarde.getRowCount() == 0){
                message.setText("La table est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un item de la table");
            }
        }
        
        else{
            
            Waregame.partieSauvegarderAJoueur = Waregame.tableauDesauvegarde[choix];
            
            //Waregame.partieSauvegarderAJoueur.afficherSauvegarde();
            
            Waregame.nom_joueur1 = Waregame.partieSauvegarderAJoueur.nom_joueur1 ;
            Waregame.num_tour_joueur1 = Waregame.partieSauvegarderAJoueur.num_tour_joueur1 ;
            Waregame.nom_joueur2 = Waregame.partieSauvegarderAJoueur.nom_joueur2 ;
            Waregame.num_tour_joueur2 = Waregame.partieSauvegarderAJoueur.num_tour_joueur2 ;
            
            FenetreJeu.remplirToutesLesCellules();
            
            for(int i=0 ; i< Waregame.partieSauvegarderAJoueur.tab.length ; i++ ){
                
                if(Waregame.partieSauvegarderAJoueur.tab[i] != null)
                    FenetreJeu.remplirCellule(Waregame.tabCellule[Waregame.partieSauvegarderAJoueur.tab[i].id_cellule], Waregame.partieSauvegarderAJoueur.tab[i].unite );
                    
            }
            
            if( (Waregame.num_tour_joueur1 == 0 && Waregame.num_tour_joueur2 == 0)  || (Waregame.nombreUniteRestant(1) == 0) || (Waregame.nombreUniteRestant(2) == 0) ){
                Waregame.id_joueur_courant = 0 ;
            }
            
            
            
            Waregame.fj.PanelEntete.setLayout(new BorderLayout());
            Waregame.fj.PanelEntete.removeAll();
            //PanelJeuEnCours jp_gc = new PanelJeuEnCours();
            PanelJeuEnCours jp_gc = new PanelJeuEnCours();
            Waregame.fj.PanelEntete.add(jp_gc);
            Waregame.fj.PanelEntete.revalidate();
            
            
            this.dispose();
            //lancer la focntion pour dessinner la partie
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageSauvegarde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageSauvegarde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageSauvegarde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageSauvegarde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageSauvegarde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_sauvegarde;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
