/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.waregame;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author semje
 */
public class PanelJeuEnCours extends javax.swing.JPanel {

    /**
     * Creates new form PanelJeuEnCours
     */
    
    
    public PanelJeuEnCours() {
        
        initComponents();
        deplacement.setText("Pts de deplacement montage : "+ Waregame.ptsDplacement_montage + " - Pts de deplacement foret : "+ Waregame.ptsDplacement_foret + " - Pts de deplacement village : "+ Waregame.ptsDplacement_village + " - Pts de deplacement plaine : " + Waregame.ptsDplacement_plaine + " - Pts de deplacement riviere : " + Waregame.ptsDplacement_riviere );
        
        
        nom_j1.setText(Waregame.nom_joueur1);
        nom_j2.setText(Waregame.nom_joueur2);
        
        if(Waregame.tableauDesauvegarde != null){
            
            if( Waregame.num_tour_joueur2 > Waregame.num_tour_joueur1 ){
                Waregame.id_joueur_courant = 2 ;
                PanelJeuEnCours.nom_joueur_courant.setText(Waregame.nom_joueur2 );
            }
            
            else{
                Waregame.id_joueur_courant = 1 ;
                PanelJeuEnCours.nom_joueur_courant.setText(Waregame.nom_joueur1);
            }
            
            num_tour_j1.setText("Tour joueur 1 restant : " + Waregame.num_tour_joueur1);
            num_tour_j2.setText("Tour joueur 2 restant : " + Waregame.num_tour_joueur2);
        }
        
        else{
            nom_joueur_courant.setText(Waregame.nom_joueur1);
            Waregame.id_joueur_courant = 1 ;
            num_tour_j1.setText("Tour joueur 1 restant : " + Waregame.nombreMaxTourAjouer);
            num_tour_j2.setText("Tour joueur 2 restant : " + Waregame.nombreMaxTourAjouer);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nom_j1 = new javax.swing.JLabel();
        nom_j2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deplacement = new javax.swing.JLabel();
        jPanel_infos_unite = new javax.swing.JPanel();
        nom_unite = new javax.swing.JLabel();
        affinite_unite = new javax.swing.JLabel();
        attaque_defense_unite = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        num_tour_j1 = new javax.swing.JLabel();
        num_tour_j2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom_joueur_courant = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        deplacement_courant = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        nom_j1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nom_j1.setForeground(new java.awt.Color(255, 153, 153));
        nom_j1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nom_j1.setText("Joueur1");

        nom_j2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nom_j2.setForeground(new java.awt.Color(255, 153, 153));
        nom_j2.setText("Joueur2");

        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VS");

        deplacement.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        deplacement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deplacement.setText("deplacement");

        jPanel_infos_unite.setBackground(new java.awt.Color(255, 255, 255));

        nom_unite.setText("Unité");

        affinite_unite.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        affinite_unite.setText("| Affinité : nom terrain");

        attaque_defense_unite.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        attaque_defense_unite.setText("| Attaque : xx, Defense : xx, Déplacement : xx, Vision : xx");

        javax.swing.GroupLayout jPanel_infos_uniteLayout = new javax.swing.GroupLayout(jPanel_infos_unite);
        jPanel_infos_unite.setLayout(jPanel_infos_uniteLayout);
        jPanel_infos_uniteLayout.setHorizontalGroup(
            jPanel_infos_uniteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infos_uniteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_infos_uniteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom_unite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(affinite_unite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attaque_defense_unite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_infos_uniteLayout.setVerticalGroup(
            jPanel_infos_uniteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infos_uniteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nom_unite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(affinite_unite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attaque_defense_unite)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Sauvegarder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Quitter la partie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        num_tour_j1.setText("Nombre tour joueur 1");

        num_tour_j2.setText("Nombre tour joueur 1");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Tour de :");

        nom_joueur_courant.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nom_joueur_courant.setForeground(new java.awt.Color(0, 204, 204));
        nom_joueur_courant.setText("Joueur 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num_tour_j1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(num_tour_j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nom_joueur_courant, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(num_tour_j1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nom_joueur_courant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num_tour_j2)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        deplacement_courant.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        deplacement_courant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deplacement_courant.setText("0");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pts déplacement restant :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deplacement_courant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deplacement_courant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom_j1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel_infos_unite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(nom_j2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deplacement)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_j1)
                    .addComponent(jLabel3)
                    .addComponent(nom_j2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_infos_unite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int choix = JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir quitter la partie ?");

        if (choix == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, "Vous avez choisi de continuer !");
            FenetreJeu.remplirToutesLesCellules();
            
            Waregame.fj.PanelEntete.setLayout(new BorderLayout());
            Waregame.fj.PanelEntete.removeAll();
            //PanelJeuEnCours jp_gc = new PanelJeuEnCours();
            PanelDebut jp_gc = new PanelDebut();
            Waregame.fj.PanelEntete.add(jp_gc);
            Waregame.fj.PanelEntete.revalidate();
            
            Waregame.id_joueur_courant = 0 ;
        
        } else {
            //JOptionPane.showMessageDialog(null, "Vous avez choisi de ne pas continuer.");
        }
        
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if( (Waregame.num_tour_joueur1 == 0 && Waregame.num_tour_joueur2 == 0)  || (Waregame.nombreUniteRestant(1) == 0) || (Waregame.nombreUniteRestant(2) == 0) ){
            
            JOptionPane.showMessageDialog(null, "Cette partie est une partie qui est dejà achevée !", "Sauvegarde non autorisée !", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else{
            int choix = JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir sauvegarder la partie ?");

            if (choix == JOptionPane.YES_OPTION) {
                //JOptionPane.showMessageDialog(null, "Vous avez choisi de continuer !");
                Sauvegarde s = new Sauvegarde(Waregame.nom_joueur1, Waregame.num_tour_joueur1, Waregame.nom_joueur2, Waregame.num_tour_joueur2, Waregame.tabCellule);
                s.SauvegardeFichier();

            } else {
                //JOptionPane.showMessageDialog(null, "Vous avez choisi de ne pas continuer.");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel affinite_unite;
    public static javax.swing.JLabel attaque_defense_unite;
    private javax.swing.JLabel deplacement;
    public static javax.swing.JLabel deplacement_courant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_infos_unite;
    private javax.swing.JLabel nom_j1;
    private javax.swing.JLabel nom_j2;
    public static javax.swing.JLabel nom_joueur_courant;
    public static javax.swing.JLabel nom_unite;
    public static javax.swing.JLabel num_tour_j1;
    public static javax.swing.JLabel num_tour_j2;
    // End of variables declaration//GEN-END:variables
}
